name: Test fixed-search-strategy-template-processing-module

on:
  pull_request:
    branches: [main]
    paths:
      - 'fixed-search-strategy-template-processing-module/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-fixed-search-strategy-template-processing-module:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run common checks for fixed-search-strategy-template-processing-module component
        uses: ostis-ai/test-conan@0.1.0
        with:
          directory: 'fixed-search-strategy-template-processing-module'
          configure-preset: release-with-tests-conan
          build-preset: release
